"""
Entry point for model training and evaluation.

This script:
  1. Loads features from `data/features.csv` (generated by `src/extract_features.py`)
  2. If LOAD_MODEL is False (default): performs 5-fold patient-level cross-validation
     over three classifiers (kNN, Logistic Regression, Decision Tree),
     trains each on the train split, evaluates on the held-out test split,
     saves each trained model and its predictions, and prints comparison metrics.
  3. If LOAD_MODEL is True: loads the saved final model and writes its predictions
     on the current features without any retraining.

TA workflow:
  - Update paths in `src/extract_features.py` to point to the new images/masks
  - Run: `python src/extract_features.py`        (regenerates data/features.csv)
  - Set `LOAD_MODEL = True` below
  - Run: `python main.py`                        (loads model, writes predictions)

Usage (from project root):
    python main.py
"""
import os
import joblib
import numpy as np
import pandas as pd

from sklearn.model_selection import GroupShuffleSplit, GroupKFold
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier


# ---------------------------------------------------------------------------
# Configuration -- the only knobs a TA may need to change
# ---------------------------------------------------------------------------
LOAD_MODEL  = True                           # True: skip training, just predict

FEATURES_CSV = './data/features.csv'           # produced by src/extract_features.py
METADATA_CSV = './data/new_metadata.csv'       # has img_id, patient_id, diagnostic

MODELS_DIR      = './results/models'
PREDICTIONS_DIR = './results/predictions'
FINAL_MODEL     = os.path.join(MODELS_DIR, 'final_model.pkl')
FINAL_PRED      = os.path.join(PREDICTIONS_DIR, 'final_predictions.csv')

CANCEROUS = ['BCC', 'MEL', 'SCC']
RANDOM_STATE = 42

os.makedirs(MODELS_DIR,      exist_ok=True)
os.makedirs(PREDICTIONS_DIR, exist_ok=True)


# ---------------------------------------------------------------------------
# Data loading -- shared by both modes
# ---------------------------------------------------------------------------
def load_data():
    """Read features, attach diagnostic + patient_id from metadata, return df."""
    df   = pd.read_csv(FEATURES_CSV)
    meta = pd.read_csv(METADATA_CSV)
    df   = df.merge(meta[['img_id', 'patient_id', 'diagnostic']],
                    on='img_id', how='left')
    df   = df.dropna(subset=['patient_id', 'diagnostic'])
    df['label'] = df['diagnostic'].isin(CANCEROUS).astype(int)

    exclude = ['img_id', 'patient_id', 'diagnostic', 'label',
               'processing_status', 'error_message']
    feature_cols = [c for c in df.columns if c not in exclude]
    print(f'Loaded {len(df)} lesions with {len(feature_cols)} feature columns')
    return df, feature_cols


def split_train_test(df, feature_cols):
    """Patient-level 80/20 train/test split."""
    X = df[feature_cols]
    y = df['label']
    groups = df['patient_id']

    gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=RANDOM_STATE)
    train_idx, test_idx = next(gss.split(X, y, groups))
    return X, y, groups, train_idx, test_idx


def evaluate_on_test(model, X_test, y_test):
    """Compute the standard metric set and return them as a dict."""
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]
    return {
        'accuracy':  accuracy_score(y_test, y_pred),
        'precision': precision_score(y_test, y_pred),
        'recall':    recall_score(y_test, y_pred),
        'f1':        f1_score(y_test, y_pred),
        'auc':       roc_auc_score(y_test, y_prob),
        'y_pred':    y_pred,
        'y_prob':    y_prob,
    }


# ---------------------------------------------------------------------------
# Model definitions -- one factory per classifier with the hyperparameter grid
# ---------------------------------------------------------------------------
def make_lr(C):
    return Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler',  StandardScaler()),
        ('logreg',  LogisticRegression(C=C, max_iter=1000,
                                       class_weight='balanced',
                                       solver='liblinear')),
    ])


def make_knn(k):
    return Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler',  StandardScaler()),
        ('knn',     KNeighborsClassifier(n_neighbors=k)),
    ])


def make_dt(depth):
    return Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('dt',      DecisionTreeClassifier(max_depth=depth,
                                           random_state=RANDOM_STATE)),
    ])


CLASSIFIERS = {
    'LR':  (make_lr,  [0.01, 0.1, 1, 10, 100], 'C'),
    'kNN': (make_knn, [3, 5, 7, 9, 11],         'k'),
    'DT':  (make_dt,  [2, 4, 6, 8, 10],         'max_depth'),
}


def cv_select_best_hp(make_fn, hp_values, X_train, y_train, groups_train):
    """5-fold patient-level CV; return (best_hp, mean_auc, per-fold AUCs)."""
    gkf = GroupKFold(n_splits=5)
    best_hp, best_auc, best_folds = None, -1.0, None
    for hp in hp_values:
        fold_aucs = []
        for fold_train, fold_val in gkf.split(X_train, y_train, groups_train):
            model = make_fn(hp)
            model.fit(X_train.iloc[fold_train], y_train.iloc[fold_train])
            probs = model.predict_proba(X_train.iloc[fold_val])[:, 1]
            fold_aucs.append(roc_auc_score(y_train.iloc[fold_val], probs))
        mean_auc = float(np.mean(fold_aucs))
        if mean_auc > best_auc:
            best_hp, best_auc, best_folds = hp, mean_auc, fold_aucs
    return best_hp, best_auc, best_folds


# ---------------------------------------------------------------------------
# Mode 1: train + evaluate + save (LOAD_MODEL = False)
# ---------------------------------------------------------------------------
def train_and_evaluate():
    df, feature_cols = load_data()
    X, y, groups, train_idx, test_idx = split_train_test(df, feature_cols)

    X_train = X.iloc[train_idx].fillna(0)
    X_test  = X.iloc[test_idx].fillna(0)
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
    groups_train    = groups.iloc[train_idx]

    print(f'\nTrain: {len(X_train)} | Test: {len(X_test)}')

    results = {}
    best_model_name, best_model_auc, best_model_obj = None, -1.0, None

    for name, (make_fn, hp_values, hp_label) in CLASSIFIERS.items():
        print(f'\n--- {name} ---')
        best_hp, cv_auc, fold_aucs = cv_select_best_hp(
            make_fn, hp_values, X_train, y_train, groups_train,
        )
        print(f'  best {hp_label} = {best_hp}    CV mean AUC = {cv_auc:.4f}')

        # Train final model on the whole training set
        final = make_fn(best_hp)
        final.fit(X_train, y_train)
        metrics = evaluate_on_test(final, X_test, y_test)
        print(f'  test AUC = {metrics["auc"]:.4f} | F1 = {metrics["f1"]:.4f}')

        # Save the model and the per-model test predictions
        joblib.dump(final, os.path.join(MODELS_DIR, f'{name}_model.pkl'))
        out = df.iloc[test_idx][['patient_id', 'img_id', 'diagnostic', 'label']].copy()
        out['predicted']   = metrics['y_pred']
        out['probability'] = metrics['y_prob']
        out.to_csv(os.path.join(PREDICTIONS_DIR, f'{name}_predictions.csv'),
                   index=False)

        results[name] = {
            'best_hp':     best_hp,
            'cv_auc':      cv_auc,
            'test_auc':    metrics['auc'],
            'test_f1':     metrics['f1'],
        }
        if metrics['auc'] > best_model_auc:
            best_model_name, best_model_auc, best_model_obj = name, metrics['auc'], final

    # Persist the best model and its predictions under the "final" names
    joblib.dump(best_model_obj, FINAL_MODEL)
    print(f'\nBest model on test set: {best_model_name} (AUC = {best_model_auc:.4f})')
    print(f'Saved as -> {FINAL_MODEL}')

    final_metrics = evaluate_on_test(best_model_obj, X_test, y_test)
    out = df.iloc[test_idx][['patient_id', 'img_id', 'diagnostic', 'label']].copy()
    out['predicted']   = final_metrics['y_pred']
    out['probability'] = final_metrics['y_prob']
    out.to_csv(FINAL_PRED, index=False)
    print(f'Saved final predictions -> {FINAL_PRED}')

    # Comparison summary
    print('\n=== Comparison summary ===')
    summary = pd.DataFrame(results).T[['best_hp', 'cv_auc', 'test_auc', 'test_f1']]
    print(summary.round(4))


# ---------------------------------------------------------------------------
# Mode 2: load saved model and produce predictions (LOAD_MODEL = True)
# ---------------------------------------------------------------------------
def load_and_predict():
    if not os.path.exists(FINAL_MODEL):
        raise FileNotFoundError(
            f'Saved model not found at {FINAL_MODEL}. '
            f'Run with LOAD_MODEL = False once to train and save the model.'
        )

    df, feature_cols = load_data()
    X = df[feature_cols].fillna(0)

    print(f'Loading model from {FINAL_MODEL}')
    model = joblib.load(FINAL_MODEL)

    y_pred = model.predict(X)
    y_prob = model.predict_proba(X)[:, 1]

    out = df[['patient_id', 'img_id', 'diagnostic']].copy()
    out['label']       = df['label']
    out['predicted']   = y_pred
    out['probability'] = y_prob
    out.to_csv(FINAL_PRED, index=False)
    print(f'Saved predictions -> {FINAL_PRED} ({len(out)} rows)')

    # If labels are present (same dataset), also print test-set metrics
    if df['label'].notna().any():
        print('\nMetrics on the supplied features (treat as evaluation set):')
        print(f'  Accuracy  = {accuracy_score(df["label"], y_pred):.4f}')
        print(f'  Precision = {precision_score(df["label"], y_pred):.4f}')
        print(f'  Recall    = {recall_score(df["label"], y_pred):.4f}')
        print(f'  F1        = {f1_score(df["label"], y_pred):.4f}')
        print(f'  AUC       = {roc_auc_score(df["label"], y_prob):.4f}')


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == '__main__':
    if LOAD_MODEL:
        load_and_predict()
    else:
        train_and_evaluate()
